version: '3.11'


services:
  bot:
    build: .
    restart: always
    container_name: insta_bot
    ports:
      - "8000:8000"
    env_file:
      - .env

    depends_on:
      - pg


  pg:
    image: postgres:alpine
    restart: always
    container_name: bot_con
    environment:
      POSTGRES_PASSWORD: 1
      TZ: Asia/Tashkent
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/





volumes:
  pg_data:






